filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/*.json
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: [ "logstash:5044" ]  # docker-compose 내부 컨테이너 이름
