spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"  # prometheus 엔드포인트 노출
  metrics:
    tags:
      application: my-kotlin-app